feat(ShidokaIcon): replaced carbon icon to shidoka icon
kyndryl-design-system/shidoka-foundation pull request #51
Opened 2024-10-23 11:53 UTC by kumarivijeta

## Summary

- Removed Icon component
- Carbon Icon replaced with Shidoka icon
- Added migration docs
- Impacted Component List
  - Accordian
  -Button with Icon
  -Link with Icon
  -Split Button & with Icon

## ADO Story

[TASK 1972305](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/1972305)

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [x] Noted breaking changes (if any).
- [x] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.

## Screenshot

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/befeb531-f788-465a-8fe3-5df60557a2a3">

<img width="502" alt="image" src="https://github.com/user-attachments/assets/08a705ff-3fbe-42a3-8067-4afbc630e2d2">

<img width="189" alt="image" src="https://github.com/user-attachments/assets/79a90400-ab0d-450b-82f9-f6b0cf9fbe3f">

<img width="429" alt="image" src="https://github.com/user-attachments/assets/ed3b5696-4411-40d9-9cb0-6133dda4e335">

<img width="298" alt="image" src="https://github.com/user-attachments/assets/35750cc2-14dd-4f7c-b596-1240905bf618">

<img width="505" alt="image" src="https://github.com/user-attachments/assets/e262fdf4-b3f3-4294-bd52-10c56240f904">

2024-10-23 12:29 UTC, brian-patrick-3 requested changes
1. The carbon-icons dependencies still need to be removed from package.json.
2. Remember to include the `BREAKING CHANGE:` footer in your commit messages next time.

2024-10-24 10:22 UTC, srpriyankashetty approved these changes
Verified the Accordion icons, numbering, Expand and collapse and looks fine
Verified the Button icons in Button with icon, icon only, default button in the bottom, scroll button and with secondary button
Verified the Link text icons
Verified the Split button icons and looks fine
Verified the size of the button and arrow/icon size changes as per the selection
Verified that disabling, disables the whole button with arrow/icon
Verified that disabled buttons arrow does not change on expand or collapse

2024-10-24 12:27 UTC, kumarivijeta reviewed
@brian-patrick-3  
**FYI**
The red marked icons in screenshot are not available in shidoka icons. I have requested Diana to get it added in shidoka icon library.

<img width="620" alt="image" src="https://github.com/user-attachments/assets/b9cbd10b-0bb2-41e1-81d1-012919e0b8bd">

2024-10-24 12:45 UTC, brian-patrick-3 commented
Those icons are just meant to be examples, so I don't think they need to map 1:1. Maybe just use circle stroke and warning filled.

2024-10-24 15:27 UTC, brian-patrick-3 commented on src/components/icon/Icon.mdx
> -### Gallery
One small problem here, we still need to document the usage of the logo SVG assets somewhere. Logout and switcher can be removed.

2024-10-25 13:43 UTC, merged

2024-10-25 13:48 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0-next.1 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-foundation/v/2.0.0-next.1)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-foundation/releases/tag/v2.0.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-02-12 19:10 UTC, brian-patrick-3 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kyndryl-design-system/shidoka-foundation/v/2.0.0)
- [GitHub release](https://github.com/kyndryl-design-system/shidoka-foundation/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: